"""Persisted-query sha256 hashes for PS Family GraphQL operations.

AUTO-GENERATED by research/gen_hashes.mjs. The PSN GraphQL gateway
(m.np.playstation.com) only accepts allowlisted persisted-query hashes; the app
computes each as sha256(graphql_v15.print(sortAST(addTypename(query)))). These
were reproduced offline from the reverse-engineered operation documents and
verified against the live gateway. Regenerate if the operation documents change.
"""

from __future__ import annotations

OPERATION_HASHES: dict[str, str] = {
    'ohanaDeclinePlaytime': '14ee69615cc4de63224ca9d06c59e1b708475e759eec1a811a3ddfeb290661ac',
    'ohanaDeleteAllowlistGameExceptionMutation': '477da71ad83cfc603d710f3197bea5a8714d16c80ccbcfcd3bb1abc21cdfec57',
    'ohanaGetActivityHistoryDetailData': 'ef21cce115687fc146065519fd401a8f169e8e6a0cade710277f44dd263af27c',
    'ohanaGetActivityHistoryReportData': 'dae785e22a2fc279004f3dd270b79c3967f184a63cbacd0c95443d57b505d992',
    'ohanaGetChildPresences': 'd39d11b74e66fa877544cacced1ba274eb0ff1cb3f756d216d86951124af733d',
    'ohanaGetChildPrivacySettingsV2': 'b78b3c208b319faa8bb688c92f632e271823bf9eb09746cf81945c6d9c0470ea',
    'ohanaGetCountryConfig': 'feb867aa2b93be5e3c1cefa999fca955e3938230f3867ea601c892b4c3c45db2',
    'ohanaGetCountryDetail': 'ebda4b814742d4065647e026825d0a2263a25d62b0443d7cdac6b7dc9e6ea6e8',
    'ohanaGetCurrencyDetails': '2ddedee07c312a2c9e3b5cef2c59f0f832fb64336aff01386d5e90931bb61fb3',
    'ohanaGetFamilyMembers': '0c6c570e23c0dbbd602fd4154113884d8d36b7190348b7624252b4baaa0fa9ea',
    'ohanaGetGameExceptionRequests': '314569fae003889cf6be498078ba6d1a67ad5eedfc25412fc03d548b040bf88b',
    'ohanaGetGameExceptions': 'b751f8d08a5e9f49fe773d53de1a22fd675ca929d01b13078d04cb1b0dbaead3',
    'ohanaGetPlaytime': 'bf536bc6bcffabd3544c4b36641ac0d61c08c0f507f6d46036220ec224dae2b8',
    'ohanaGetPlaytimeLimitData': '6d864cedf3f6b16238759aa5a21adfe8ba55a2c001681c8e13b44608ae549cde',
    'ohanaGetPlaytimeLimitsForEditDailyLimitScreen': 'cbafc1ba35fceb9f5df53bab4a546259c0e475afe85defa30e9c008734394b17',
    'ohanaGetPlaytimeTimezone': 'af415de937c2005f4351cd4ff995118e19db822f44b97eca5a17218133c9cc6d',
    'ohanaGetSettingsTemplatesV2': 'acc4b8d752c5fbc576ed078cea6862e187adda54f153e054e881d54bd9bb82a0',
    'ohanaGetSetupDailyLimitData': '2df1ba1d82ddd3886ce0c7cf2223479b2e0a142c73012645323165e11dd91e0f',
    'ohanaGetSpending': 'b05007107f4885bceb7bdc2115dc2868e18592ea86454bd02b34a47ff2060067',
    'ohanaGetSupportedParentalControls': '594fcea0ab32e47389a12e1dbeabc14f679a5127905b8ffc92abce0ee8e5ccf0',
    'ohanaGetSupportedSpendingLimits': '29c3bedad58d44005aec7d49eec9d0c70c5eb0abe79be6ed81d4a0b6b28adafd',
    'ohanaGetWalletBalanceQuery': '292b652eea20ba5dfd2446c4d979fa0454bb9316980088742a42d44fa373791d',
    'ohanaGetWhenPlaytimeEndsData': '91f96139d644109cc6ed79fb2454c93db24da4d8c99976ceef27072fb675ce30',
    'ohanaGetWhySetPlaytimeScreenData': '184b3c927328606761ace77977816ca0eda828382cb2ec2755235a4128864285',
    'ohanaUpdateAgeLevel': '98a085637d5fd1b6f35fde1dded5c36cea8b5d3e62fd0a20831fe7b5659112dd',
    'ohanaUpdateBluerayAgeContent': '3e4d4941cc684b5e6f2f8fc4245e51d747352ec90fb5e6c6d0aa78e31e2f4263',
    'ohanaUpdateBulkParentalControls': 'e96407de3284088e4288263c5bd8f14c27fae2cbcb631f9386d0f14c93a8693b',
    'ohanaUpdateChildPrivacySettingsV2': '1eb602e6cc10636e8bf5e5557adf5008a12658c6a847760c95ccf44e4eb04074',
    'ohanaUpdateContentControl': 'c377c36f393636d3abb6689dba79a259f0e043e7c9a2303fe3b66cf08fdad432',
    'ohanaUpdateDiscContentCountry': '0ec98f5b6d626ea994357891d5eae7d45ccc259f8238bf48eec02f3be8394b29',
    'ohanaUpdateDvdContent': '482551014d16f7214bff21c0e275dd604de97a833016130729657f8155f94fe7',
    'ohanaUpdateFreeCommunication': 'a49cbabfb74f27850b15881e24e92ca94b63667fbe70804e83eeb2e5b1290452',
    'ohanaUpdateGameContent': '0d61f211b0daf1e99aa52b7104d63b6d87958a6fbe5f5e156ba2d468633cc7fd',
    'ohanaUpdateGameException': 'aed232ba4e86a8bae555f1eef06ca88363096dfcb1314b98a64ef9cd9064b2f4',
    'ohanaUpdateInternetBrowser': '3746b5e6a3915e98f3a5db82613f25597b789717d1375d742620efbdcb7f8aeb',
    'ohanaUpdatePlaytimeOnLimitReached': '31c6c938239a173a63db2f1b3522b37bca7001adb3041063187ad5c3c1d04d3b',
    'ohanaUpdatePlaytimeSchedule': '6dbab3de7dfd49e7bcaedd01d394dbcc58ebd4431084204a5731aa2eb6799595',
    'ohanaUpdatePlaytimeTimezone': '661d9abe8430894f1803a9efcf4fce82fd3479288dd19d3690d5194bc8427d21',
    'ohanaUpdatePrivacyRestrictionMode': '658377cee8657542646c44f3483fe1a5dd1bf54cad4e12aa15c9d5216d78cc4a',
    'ohanaUpdateSpendingLimit': '3cb96ea0813939c625510b073630eea8e04348a14ceb395fbe20c739adca6d09',
    'ohanaUpdateVrApp': 'c1a33f22951f4cb738dc4ad7c86fe27f467a1597cecf29279f2ccc8c6a0cc53e',
    'updateTodaysPlaytimeLimit': '47b018902e3f7da770a63f96ecb17d602710e9df4c8efb3778a985d48c089d5f',
}

# --- Captured persisted-query hashes (override) -----------------------------
# These write operations' hashes CANNOT be reproduced from the bundle gql
# sources. The recipe is NOT the problem -- it is provably correct
# (sha256(graphql@15.print(sortAST(addTypename(doc)))) reproduces the live app's
# hash for ohanaUpdatePlaytimeOnLimitReached byte-for-byte, plus every read
# query). The DOCUMENT is: these mutations are assembled at runtime in Hermes JS
# (operation name + return selection interpolated into a shared template), so the
# exact document hashed never exists as a static string, the persisted-query
# protocol never transmits it (only the hash), and it is not reconstructible --
# with the recipe AND the target hash known, 76 candidate documents for
# ohanaUpdateGameContent failed to reproduce dcf1ff40 (the hashes are also not
# literals anywhere in the APK). They
# were CAPTURED from genuine live app traffic (PS Family 26.4.0 running
# unmodified on a rooted Android emulator, intercepted with a Frida SSL_write
# hook) and each was verified present in Sony's gateway persisted-query
# safelist. Captured 2026-06-24.
CAPTURED_HASHES: dict[str, str] = {
    # play-time (add / remove time for today)
    'updateTodaysPlaytimeLimit': '2b86536fc8f6836ad033649722208f5d1c4baa9c591096dd55fd35ff42681517',
    # parental controls (updateParentalControls family) -- variables:
    #   {accountId, parentalControls: {<field>: <value>}}
    'ohanaUpdateInternetBrowser': '6e7cb7b1eb090c5cfaf2e83f4e45c7b08bddd4a85dee2877bd288577c67d2135',
    'ohanaUpdateVrApp': '0fa4754eb6994f1d6dc868b620b2ecbb132a3b0c23491d5a468cd0f113c7ea22',
    'ohanaUpdateFreeCommunication': '2fe2500a956ac99d13f69b4f5f450112f3ad158b3a4379e3a1762036431a2ef5',
    'ohanaUpdateContentControl': '822b9dc947842cd7f7e2c8e22e54807336a8bc8521d1fea01bb162228e4e3592',
    'ohanaUpdateAgeLevel': '0b0ae8d1da275a9af74d0bf576f3affcd02362bc14972b9b4fea9d4219567df1',
    'ohanaUpdateGameContent': 'dcf1ff4051882170d280fd8805c0070108671f487072662a2dd3e6398634828f',
    'ohanaUpdateSpendingLimit': 'f6b17484491945c40896adb2b6bb138b5415f2cf7454e6a25b6305269293c0ad',
    # privacy
    'ohanaUpdatePrivacyRestrictionMode': '40ea22d951d009376595a5216f7d3c6bc27d6f8cda51f175cc78d66c7d87ccb1',
    'ohanaUpdateChildPrivacySettingsV2': 'fe3d1dce436eef15c15774637c8e69409f9088067ad2226ff5eb274155ed3b83',
    # bulk update -- applies a whole ParentalControls preset in one request;
    # variables: {accountId, parentalControls: {ageLevel, bluerayAgeContent,
    #   contentControl, discContentCountry, dvdContent, freeCommunication,
    #   gameContent, internetBrowser, spendingLimit, vrApp}} (all fields at once;
    #   discContentCountry is an ISO country code, the rest are numeric strings).
    'ohanaUpdateBulkParentalControls': 'd327d063c19a5673c05f069ea0068eb564fbd3236a6f43dbe02a970516a3f06c',
    # game exceptions (approve / revoke an allow-listed restricted game) --
    # variables: ohanaUpdateGameException{accountId, updateGameExceptionInput:
    #   {titleId, exceptionType:"GAME_BOOT", entryType:"title",
    #    requestAnswer:"APPROVE"|"DENY"}};
    # ohanaDeleteAllowlistGameExceptionMutation{accountId,
    #   deleteAllowlistGameExceptionInput:{entryType:"title",
    #    exceptionType:"GAME_BOOT", titleId}}
    'ohanaUpdateGameException': '1786ed5f49a907f82b334583f0de014451be2f1a9ee87108f55c028abe895c47',
    'ohanaDeleteAllowlistGameExceptionMutation': '9f638e541ff08d8339b6e231dc93476792ad71917e97329a1ff33f5b3cdd4649',
    # TODO(capture): the 3 ops below still hold their (incorrect) computed hash
    # from OPERATION_HASHES above and will raise PsnFamilyApiError ("not
    # whitelisted") until captured the same way (rooted-emulator + Frida
    # SSL_write; see research/REVERSE_ENGINEERING.md). Not triggerable from the
    # parent app on a digital (no-disc) account -- there is no Blu-ray/disc/DVD
    # content UI to drive them:
    #   - ohanaUpdateBluerayAgeContent
    #   - ohanaUpdateDiscContentCountry
    #   - ohanaUpdateDvdContent
    # NB: ohanaUpdateBulkParentalControls (captured above) CAN write
    # bluerayAgeContent / discContentCountry / dvdContent as part of a full
    # preset, so those three values are reachable today via set_bulk_parental_controls().
}
OPERATION_HASHES.update(CAPTURED_HASHES)

__all__ = ['CAPTURED_HASHES', 'OPERATION_HASHES']
