"""Persisted-query sha256 hashes for PS Family GraphQL operations.

AUTO-GENERATED by research/gen_hashes.mjs. The PSN GraphQL gateway
(m.np.playstation.com) only accepts allowlisted persisted-query hashes. Each
is computed offline as::

    sha256(graphql@14.print(sortAST(addTypenameToDocument(parse(source)))))

The graphql **v14** printer is essential: it keeps long argument lists on a
single line, whereas v15/v16 reformat them across lines -- so v15/v16 reproduce
the short-argument ops (most queries) but NOT the long-argument ones (the
updateParentalControls family, updateTodaysPlaytimeLimit, ...). The recipe was
recovered by decompiling the app's persisted-query-id closure from the Hermes
bytecode (research/CAPTURE_FINDINGS.md) and every value was confirmed against
the live gateway safelist (and, for 13 ops, against captured app traffic).
Regenerate if the operation documents change.
"""

from __future__ import annotations

OPERATION_HASHES: dict[str, str] = {
    'ohanaDeclinePlaytime': '14ee69615cc4de63224ca9d06c59e1b708475e759eec1a811a3ddfeb290661ac',
    'ohanaDeleteAllowlistGameExceptionMutation': '9f638e541ff08d8339b6e231dc93476792ad71917e97329a1ff33f5b3cdd4649',
    'ohanaGetActivityHistoryDetailData': 'ef21cce115687fc146065519fd401a8f169e8e6a0cade710277f44dd263af27c',
    'ohanaGetActivityHistoryReportData': 'dae785e22a2fc279004f3dd270b79c3967f184a63cbacd0c95443d57b505d992',
    'ohanaGetChildPresences': 'd39d11b74e66fa877544cacced1ba274eb0ff1cb3f756d216d86951124af733d',
    'ohanaGetChildPrivacySettingsV2': 'b78b3c208b319faa8bb688c92f632e271823bf9eb09746cf81945c6d9c0470ea',
    'ohanaGetCountryConfig': 'feb867aa2b93be5e3c1cefa999fca955e3938230f3867ea601c892b4c3c45db2',
    'ohanaGetCountryDetail': 'ebda4b814742d4065647e026825d0a2263a25d62b0443d7cdac6b7dc9e6ea6e8',
    'ohanaGetCurrencyDetails': '2ddedee07c312a2c9e3b5cef2c59f0f832fb64336aff01386d5e90931bb61fb3',
    'ohanaGetFamilyMembers': '0c6c570e23c0dbbd602fd4154113884d8d36b7190348b7624252b4baaa0fa9ea',
    'ohanaGetGameExceptionRequests': '314569fae003889cf6be498078ba6d1a67ad5eedfc25412fc03d548b040bf88b',
    'ohanaGetGameExceptions': 'b751f8d08a5e9f49fe773d53de1a22fd675ca929d01b13078d04cb1b0dbaead3',
    'ohanaGetPlaytime': 'bf536bc6bcffabd3544c4b36641ac0d61c08c0f507f6d46036220ec224dae2b8',
    'ohanaGetPlaytimeLimitData': '6d864cedf3f6b16238759aa5a21adfe8ba55a2c001681c8e13b44608ae549cde',
    'ohanaGetPlaytimeLimitsForEditDailyLimitScreen': 'cbafc1ba35fceb9f5df53bab4a546259c0e475afe85defa30e9c008734394b17',
    'ohanaGetPlaytimeTimezone': 'af415de937c2005f4351cd4ff995118e19db822f44b97eca5a17218133c9cc6d',
    'ohanaGetSettingsTemplatesV2': 'acc4b8d752c5fbc576ed078cea6862e187adda54f153e054e881d54bd9bb82a0',
    'ohanaGetSetupDailyLimitData': '2df1ba1d82ddd3886ce0c7cf2223479b2e0a142c73012645323165e11dd91e0f',
    'ohanaGetSpending': 'b05007107f4885bceb7bdc2115dc2868e18592ea86454bd02b34a47ff2060067',
    'ohanaGetSupportedParentalControls': '594fcea0ab32e47389a12e1dbeabc14f679a5127905b8ffc92abce0ee8e5ccf0',
    'ohanaGetSupportedSpendingLimits': '29c3bedad58d44005aec7d49eec9d0c70c5eb0abe79be6ed81d4a0b6b28adafd',
    'ohanaGetWalletBalanceQuery': '292b652eea20ba5dfd2446c4d979fa0454bb9316980088742a42d44fa373791d',
    'ohanaGetWhenPlaytimeEndsData': '91f96139d644109cc6ed79fb2454c93db24da4d8c99976ceef27072fb675ce30',
    'ohanaGetWhySetPlaytimeScreenData': '184b3c927328606761ace77977816ca0eda828382cb2ec2755235a4128864285',
    'ohanaUpdateAgeLevel': '0b0ae8d1da275a9af74d0bf576f3affcd02362bc14972b9b4fea9d4219567df1',
    'ohanaUpdateBluerayAgeContent': '4edea1bf7e390ae290e066367f53df35bc2d5b09926fd3584c50441e98a70225',
    'ohanaUpdateBulkParentalControls': 'd327d063c19a5673c05f069ea0068eb564fbd3236a6f43dbe02a970516a3f06c',
    'ohanaUpdateChildPrivacySettingsV2': 'fe3d1dce436eef15c15774637c8e69409f9088067ad2226ff5eb274155ed3b83',
    'ohanaUpdateContentControl': '822b9dc947842cd7f7e2c8e22e54807336a8bc8521d1fea01bb162228e4e3592',
    'ohanaUpdateDiscContentCountry': '34c91789b2cb50d75c8ea7f55cd8636058d4d42582b8c3e25fe0ac9ccb8eb4e2',
    'ohanaUpdateDvdContent': 'e02af278d5d0162fc7f25bb98967736ea9499369b111fd203e155a4bd7fc486f',
    'ohanaUpdateFreeCommunication': '2fe2500a956ac99d13f69b4f5f450112f3ad158b3a4379e3a1762036431a2ef5',
    'ohanaUpdateGameContent': 'dcf1ff4051882170d280fd8805c0070108671f487072662a2dd3e6398634828f',
    'ohanaUpdateGameException': '1786ed5f49a907f82b334583f0de014451be2f1a9ee87108f55c028abe895c47',
    'ohanaUpdateInternetBrowser': '6e7cb7b1eb090c5cfaf2e83f4e45c7b08bddd4a85dee2877bd288577c67d2135',
    'ohanaUpdatePlaytimeOnLimitReached': '31c6c938239a173a63db2f1b3522b37bca7001adb3041063187ad5c3c1d04d3b',
    'ohanaUpdatePlaytimeSchedule': '6dbab3de7dfd49e7bcaedd01d394dbcc58ebd4431084204a5731aa2eb6799595',
    'ohanaUpdatePlaytimeTimezone': '661d9abe8430894f1803a9efcf4fce82fd3479288dd19d3690d5194bc8427d21',
    'ohanaUpdatePrivacyRestrictionMode': '40ea22d951d009376595a5216f7d3c6bc27d6f8cda51f175cc78d66c7d87ccb1',
    'ohanaUpdateSpendingLimit': 'f6b17484491945c40896adb2b6bb138b5415f2cf7454e6a25b6305269293c0ad',
    'ohanaUpdateVrApp': '0fa4754eb6994f1d6dc868b620b2ecbb132a3b0c23491d5a468cd0f113c7ea22',
    'updateTodaysPlaytimeLimit': '2b86536fc8f6836ad033649722208f5d1c4baa9c591096dd55fd35ff42681517',
}

__all__ = ['OPERATION_HASHES']
